[package]
name = "monkey-interpreter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rustyline = "14.0.0"
users = "0.11.0"
once_cell = "1.19.0"